---
title: "Lubridate - labs"
output: html_notebook
---

# Practicamos con Lubridate

```{r}
library(tidyverse)
library(lubridate)
library(nycflights13)
```

```{r}
today()
```

```{r}
now()
```


## La función de Lubridate `ymd`

```{r}
# Transformar fehcas en formato cadena de texto
ymd("2020-11-21")
```

```{r}
mdy("November 28th, 2020")
```

```{r}
dmy("28-November-2020")
```

```{r}
ymd(20201121)
```


## Función Lubridate `ymd_hms`

```{r}
ymd_hms("2020-11-21 13:50:11")
```

```{r}
mdy_hm("11/21/2020 13:50")
```

```{r}
ymd_hms("2020-11-21 13:50:11", tz = "Europe/Madrid")
```


```{r}
ymd_hms("2020-11-21 13:50:11", tz = "Australia/Sydney")
```


```{r}
ymd("2020-11-30", tz = "CET") # investigad....
```


```{r}
ymd("2020-11-21", tz = "CET")
```


```{r}
ymd(20201121, tz = "Europe/Madrid")
```


```{r}
flights %>%
  select(year, month, day, hour, minute)
```


```{r}
# Transformación a fechas
flights %>%
  select(year, month, day, hour, minute) %>%
  mutate(
  departure = make_datetime(year, month, day, hour, minute, tz='GMT')
  )
```


```{r}
# Probamos con POSIXlt

```


```{r}
# Crear la transformación del datetime en variables dep_time y arr_time
make_datetime_100 <- function(year, month, day, time){
  make_datetime(year, month, day, time %/% 100, time %% 100)
}
```


```{r}
flights_dt <- flights %>%
  filter(!is.na(dep_time), !is.na(arr_time)) %>%
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time = make_datetime_100(
      year, month, day, sched_dep_time
    ),
    sched_arr_time = make_datetime_100(
      year, month, day, sched_arr_time
    ),
    air_time = make_datetime_100(year, month, day, air_time)
  ) %>%
  select(origin, dest, ends_with("delay"), ends_with("time"))
```


```{r}
# Visualizamos los datos ggplot2
flights_dt %>%
  ggplot(aes(dep_time)) +
  geom_freqpoly(binwidth = 86400) # este valor se corresponde a los segundos de un día
```


```{r}
# Visualizamos por día
flights_dt %>%
  filter(dep_time < ymd(20130102)) %>%
  ggplot(aes(dep_time)) + 
  geom_freqpoly(binwidth = 600) # son segundos igual a 10 minutos
```


## Transformación de otro tipo de formato fecha

```{r}
as_datetime(today())
```

```{r}
as_date(now())
```

```{r}
# En muchos casos tenemos un formato del tipo UNIX - 1970-01-01
as_datetime(60 * 60 * 10)
```

```{r}
as_date(365 * 10 + 2)
```


## Componentes de un `date-time`

```{r}
datetime <- ymd_hms("2020-11-28 13:20:16")
datetime
```

```{r}
# transformar en anyos
year(datetime)

# transformamos en mes
month(datetime)

# transformamos en día
mday(datetime)

# transformamos en día del anyo
yday(datetime)

# en día de la semana
wday(datetime)

```


```{r}
# podemos asignarle atributos a month() de forma literal
month(datetime, label = TRUE)
```



```{r}
# podemos asignarle atributos a wday() de forma literal
wday(datetime, label = TRUE)

# días de la semana de DOM - LUN por defecto 
wday(datetime, label = TRUE, abbr = FALSE)

# días de la semana de LUN - DOM
wday(datetime, label = TRUE, abbr = FALSE, locale = "Italian", week_start = 1)

# meses del año 
month(datetime, label = TRUE, abbr = FALSE, locale = "French")
```


```{r}
# Visualizamos los días de la semana aplicado a flights
flights_dt %>%
  mutate(wday = wday(dep_time, label = TRUE, abbr = FALSE, locale = 'german', week_start = 1)) %>%
  ggplot(aes(x = wday)) +
  geom_bar()
```


## Representación de los vuelos con retraso

```{r}
flights_dt %>%
  mutate(minute = minute(dep_time)) %>%
  group_by(minute) %>%
  summarize(
    avg_delay = mean(arr_delay, na.rm = TRUE),
    n = n()) %>%
  ggplot(aes(minute, avg_delay)) +
  geom_line()
```



```{r}
sched_dep <- flights_dt %>%
  mutate(minute = minute(sched_dep_time)) %>%
  group_by(minute) %>%
  summarize(
    avg_delay = mean(arr_delay, na.rm = TRUE),
    n = n())

  ggplot(sched_dep, aes(minute, avg_delay)) +
  geom_line()
```


## Duration, Periods, Intervals

```{r}
# Duration es igual a la diferencia entre fecha actual (periodo) y fecha inicio
age <- today() - ymd(19800101)
age
```

```{r}
as.duration(age) # esta función siempre devolverá los segundos de duración
```


```{r}
# Separamos por componentes del tiempo
dseconds(15)
dminutes(10)
dhours(c(12,14))

```

```{r}
ddays(0:5)

dweeks(3)

dyears(1)
```
 















